architecture: replication

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: password
  sentinel: true

master:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  count: 1
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi

replica:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  replicaCount: 1
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi

sentinel:
  enabled: true
  masterSet: foreman
  quorum: 1
  automateClusterRecovery: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true