prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 128Mi
  prometheusConfigReloader:
    resources:
      limits:
        cpu: 5m
        memory: 50Mi
      requests:
        cpu: 1m
        memory: 25Mi
  # networkPolicy:
  #   enabled: true

prometheus:
  # networkPolicy:
  #   enabled: true
  prometheusSpec:
    resources:
      requests:
        cpu: "50m"
        memory: "512Mi"
      limits:
        cpu: "100m"
        memory: "640Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 10Gi
    enableRemoteWriteReceiver: true
    enableFeatures:
      - native-histograms
      - exemplar-storage
    routePrefix: "/"
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /

alertmanager:
  enabled: true
  # networkPolicy:
  #   enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: "2m"
        memory: "72Mi"
      limits:
        cpu: "3m"
        memory: "96Mi"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          resources:
            requests:
              storage: 10Gi
    routePrefix: "/"
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /

grafana:
  # networkPolicy:
  #   enabled: true
  persistence:
    enabled: true
    storageClassName: oci-bv
    size: 10Gi
  resources:
    limits:
      cpu: "100m"
      memory: "384Mi"
    requests:
      cpu: "20m"
      memory: "200Mi"
  sidecar:
    resources:
      limits:
        cpu: "100m"
        memory: "160Mi"
      requests:
        cpu: "5m"
        memory: "96Mi"
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  adminPassword: admin
  grafana.ini:
    server:
      serve_from_sub_path: false
  route:
    main:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: kube-system
          sectionName: https
      matches:
        - path:
            type: PathPrefix
            value: /
