apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - otel-configmap.yaml
  # - monitor-netpol.yaml

configMapGenerator:
  - name: grafana-dashboard-k6
    files:
      - k6-load-testing-slos.json=dashboards/k6.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"