clusterIssuers:
  - name: letsencrypt-prod
    spec:
      acme:
        email: "${issuer_email}"
        server: "https://acme-v02.api.letsencrypt.org/directory"
        privateKeySecretRef:
          name: letsencrypt-prod
        solvers:
          - dns01:
              cloudflare:
                email: "${issuer_email}"
                apiTokenSecretRef:
                  name: cloudflare-api
                  key: api-token 
